"""managed_chats + autoapprove + autoreact

Revision ID: 59d992f32290
Revises: c77a3096db96
Create Date: 2026-06-20 12:38:34.352947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59d992f32290"
down_revision: Union[str, Sequence[str], None] = "c77a3096db96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "managed_chats",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_type", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("added_by", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_index(op.f("ix_managed_chats_added_by"), "managed_chats", ["added_by"], unique=False)
    op.create_index(
        op.f("ix_managed_chats_is_active"), "managed_chats", ["is_active"], unique=False
    )
    op.add_column(
        "chat_settings",
        sa.Column("autoapprove_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "chat_settings",
        sa.Column("autoreact_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "chat_settings",
        sa.Column("autoreact_emojis", sa.String(length=255), nullable=False, server_default="👍"),
    )
    op.add_column(
        "chat_settings",
        sa.Column("autoreact_random", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_settings", "autoreact_random")
    op.drop_column("chat_settings", "autoreact_emojis")
    op.drop_column("chat_settings", "autoreact_enabled")
    op.drop_column("chat_settings", "autoapprove_enabled")
    op.drop_index(op.f("ix_managed_chats_is_active"), table_name="managed_chats")
    op.drop_index(op.f("ix_managed_chats_added_by"), table_name="managed_chats")
    op.drop_table("managed_chats")
    # ### end Alembic commands ###
