"""stage 1 moderation

Revision ID: 81fb9988cc2c
Revises: bf6a9d8e4b39
Create Date: 2026-06-20 05:11:30.474019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81fb9988cc2c'
down_revision: Union[str, Sequence[str], None] = 'bf6a9d8e4b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
