"""stage 2 newcomers

Revision ID: 908526590a4c
Revises: 03e321a415f2
Create Date: 2026-06-20 05:39:11.056022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '908526590a4c'
down_revision: Union[str, Sequence[str], None] = '03e321a415f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_settings', sa.Column('captcha_type', sa.String(length=16), nullable=False, server_default='button'))
    op.add_column('chat_settings', sa.Column('quarantine_enabled', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_settings', 'quarantine_enabled')
    op.drop_column('chat_settings', 'captcha_type')
    # ### end Alembic commands ###
