"""scheduled_posts batch_id

Revision ID: a1f17a8ef47a
Revises: 59d992f32290
Create Date: 2026-06-20 13:03:59.504958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f17a8ef47a'
down_revision: Union[str, Sequence[str], None] = '59d992f32290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_posts', sa.Column('batch_id', sa.String(length=36), nullable=False, server_default=''))
    op.create_index('ix_scheduled_posts_batch_id', 'scheduled_posts', ['batch_id'])
    op.create_index(op.f('ix_scheduled_posts_batch_id'), 'scheduled_posts', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_posts_batch_id'), table_name='scheduled_posts')
    op.drop_column('scheduled_posts', 'batch_id')
    # ### end Alembic commands ###
