"""initial schema

Revision ID: bf6a9d8e4b39
Revises:
Create Date: 2026-06-20 05:02:26.565773

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf6a9d8e4b39"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_settings",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("antispam_enabled", sa.Boolean(), nullable=False),
        sa.Column("antimat_enabled", sa.Boolean(), nullable=False),
        sa.Column("antiflood_enabled", sa.Boolean(), nullable=False),
        sa.Column("captcha_enabled", sa.Boolean(), nullable=False),
        sa.Column("welcome_enabled", sa.Boolean(), nullable=False),
        sa.Column("clean_service_msgs", sa.Boolean(), nullable=False),
        sa.Column("warn_limit", sa.Integer(), nullable=False),
        sa.Column("warn_action", sa.String(length=16), nullable=False),
        sa.Column("captcha_timeout", sa.Integer(), nullable=False),
        sa.Column("flood_messages", sa.Integer(), nullable=False),
        sa.Column("flood_seconds", sa.Integer(), nullable=False),
        sa.Column("flood_mute_seconds", sa.Integer(), nullable=False),
        sa.Column("newbie_quarantine_hours", sa.Integer(), nullable=False),
        sa.Column("welcome_text", sa.Text(), nullable=False),
        sa.Column("rules_text", sa.Text(), nullable=False),
        sa.Column("welcome_delete_after", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_table(
        "moderation_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column("target_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_moderation_log_chat_id"), "moderation_log", ["chat_id"], unique=False)
    op.create_index(
        op.f("ix_moderation_log_created_at"), "moderation_log", ["created_at"], unique=False
    )
    op.create_table(
        "moderators",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("permissions", sa.String(length=255), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "user_id", name="uq_mod_chat_user"),
    )
    op.create_index(op.f("ix_moderators_chat_id"), "moderators", ["chat_id"], unique=False)
    op.create_index(op.f("ix_moderators_user_id"), "moderators", ["user_id"], unique=False)
    op.create_table(
        "scheduled_posts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("media", sa.Text(), nullable=False),
        sa.Column("buttons", sa.Text(), nullable=False),
        sa.Column("parse_mode", sa.String(length=16), nullable=False),
        sa.Column("publish_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delete_after", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("repeat_rule", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_posts_channel_id"), "scheduled_posts", ["channel_id"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_posts_publish_at"), "scheduled_posts", ["publish_at"], unique=False
    )
    op.create_table(
        "stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("metric", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "date", "metric", name="uq_stat"),
    )
    op.create_index(op.f("ix_stats_chat_id"), "stats", ["chat_id"], unique=False)
    op.create_index(op.f("ix_stats_date"), "stats", ["date"], unique=False)
    op.create_table(
        "allowed_domains",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chat_settings.chat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "domain", name="uq_domain"),
    )
    op.create_table(
        "stopwords",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("word", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chat_settings.chat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "word", name="uq_stopword"),
    )
    op.create_table(
        "warns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("history", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chat_settings.chat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "user_id", name="uq_warn_chat_user"),
    )
    op.create_index(op.f("ix_warns_user_id"), "warns", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_warns_user_id"), table_name="warns")
    op.drop_table("warns")
    op.drop_table("stopwords")
    op.drop_table("allowed_domains")
    op.drop_index(op.f("ix_stats_date"), table_name="stats")
    op.drop_index(op.f("ix_stats_chat_id"), table_name="stats")
    op.drop_table("stats")
    op.drop_index(op.f("ix_scheduled_posts_publish_at"), table_name="scheduled_posts")
    op.drop_index(op.f("ix_scheduled_posts_channel_id"), table_name="scheduled_posts")
    op.drop_table("scheduled_posts")
    op.drop_index(op.f("ix_moderators_user_id"), table_name="moderators")
    op.drop_index(op.f("ix_moderators_chat_id"), table_name="moderators")
    op.drop_table("moderators")
    op.drop_index(op.f("ix_moderation_log_created_at"), table_name="moderation_log")
    op.drop_index(op.f("ix_moderation_log_chat_id"), table_name="moderation_log")
    op.drop_table("moderation_log")
    op.drop_table("chat_settings")
    # ### end Alembic commands ###
