"""stage 4 stats roles dictionaries

Revision ID: c36e8aee021b
Revises: 17c6a4e9fe64
Create Date: 2026-06-20 06:29:07.371010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36e8aee021b'
down_revision: Union[str, Sequence[str], None] = '17c6a4e9fe64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
