"""add block_mentions to chat_settings

Revision ID: c70a1dd1f485
Revises: a1f17a8ef47a
Create Date: 2026-06-20 16:48:23.594225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70a1dd1f485'
down_revision: Union[str, Sequence[str], None] = 'a1f17a8ef47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'chat_settings',
        sa.Column(
            'block_mentions',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_settings', 'block_mentions')
    # ### end Alembic commands ###
