"""add giveaways tables

Revision ID: c77a3096db96
Revises: dc572eef6c66
Create Date: 2026-06-20 10:35:39.724156

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c77a3096db96"
down_revision: Union[str, Sequence[str], None] = "dc572eef6c66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "giveaways",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("winners_count", sa.Integer(), nullable=False),
        sa.Column("require_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("require_channel_title", sa.String(length=255), nullable=False),
        sa.Column("post_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("post_message_id", sa.Integer(), nullable=False),
        sa.Column("finish_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_giveaways_finish_at"), "giveaways", ["finish_at"], unique=False)
    op.create_table(
        "giveaway_participants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("giveaway_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["giveaway_id"], ["giveaways.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("giveaway_id", "user_id", name="uq_giveaway_user"),
    )
    op.create_index(
        op.f("ix_giveaway_participants_giveaway_id"),
        "giveaway_participants",
        ["giveaway_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_giveaway_participants_user_id"), "giveaway_participants", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_giveaway_participants_user_id"), table_name="giveaway_participants")
    op.drop_index(op.f("ix_giveaway_participants_giveaway_id"), table_name="giveaway_participants")
    op.drop_table("giveaway_participants")
    op.drop_index(op.f("ix_giveaways_finish_at"), table_name="giveaways")
    op.drop_table("giveaways")
    # ### end Alembic commands ###
