"""stage 2 quarantine

Revision ID: cdcd70cd132b
Revises: 908526590a4c
Create Date: 2026-06-20 05:50:46.928856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cdcd70cd132b"
down_revision: Union[str, Sequence[str], None] = "908526590a4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member_joins",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "user_id", name="uq_member_join"),
    )
    op.create_index(op.f("ix_member_joins_chat_id"), "member_joins", ["chat_id"], unique=False)
    op.create_index(op.f("ix_member_joins_user_id"), "member_joins", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_member_joins_user_id"), table_name="member_joins")
    op.drop_index(op.f("ix_member_joins_chat_id"), table_name="member_joins")
    op.drop_table("member_joins")
    # ### end Alembic commands ###
