"""add autoreact_join_custom

Revision ID: d8bfbba2e0d8
Revises: c70a1dd1f485
Create Date: 2026-06-20 17:17:33.884999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8bfbba2e0d8'
down_revision: Union[str, Sequence[str], None] = 'c70a1dd1f485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_settings', sa.Column('autoreact_join_custom', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_settings', 'autoreact_join_custom')
    # ### end Alembic commands ###
